### ISSUE TITLE
Account and password field shares the same validation as cell name field

### ISSUE THREAD

**Issue by dixonsiu** [fujitsu-pio/app-sample-unitadmin#8]
All three fields should have different validation according to the API specifications.

・Cell Name
→桁数：1～128
　文字種:半角英数字と-(半角ハイフン)と_(半角アンダーバー)
　ただし、先頭文字に_(半角アンダーバー)と:(コロン)は指定不可

・Account Name
→桁数：1～128
　文字種:半角英数字と下記半角記号
　-_!$*=^`{|}~.@
　ただし、先頭文字に半角記号は指定不可

・Password
→文字数：6～32文字
　文字種:半角英数字と-(半角ハイフン)と_(半角アンダーバー)

**Comment by SawamiWataru** [comment]
Describe the regular expression used in personium-core.

- Cell Name
 ^[a-zA-Z0-9][a-zA-Z0-9-_]{0,127}$

- Account Name
 ^[a-zA-Z0-9][a-zA-Z0-9-_!$*=^`{|}~.@]{0,127}$

- Password
 ^[a-zA-Z0-9-_]{0,}$
 (Checking 6 to 32 letters is carried out separately.)
